"""
model.py
--------
Person 3 – Machine Learning Model

Trains an XGBoost classifier on the feature matrix generated by Person 2.
Evaluates predictions using the F_0.5 metric.

Usage:
    python src/model.py
"""

import os
import sys
import pandas as pd
import numpy as np

sys.path.insert(0, os.path.abspath("."))
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

from sklearn.model_selection import train_test_split
from src.feature_engineering import FEATURE_COLS
from src.evaluate import f05_score

try:
    import xgboost as xgb
except ImportError:
    print("XGBoost is not installed. Please install it with: pip install xgboost")
    sys.exit(1)

SEP = "=" * 72

def main():
    print(f"\n{SEP}")
    print("  PERSON 3 · MACHINE LEARNING MODEL (XGBoost)")
    print(f"{SEP}\n", flush=True)

    # 1. Load feature matrix
    feature_file = "output/features_sample_train.csv"
    if not os.path.exists(feature_file):
        print(f"Error: Feature matrix not found at {feature_file}")
        print("Please run Person 2's pipeline first: python run_person2_pipeline.py")
        return

    print(f"[1] Loading features from {feature_file} ...")
    df = pd.read_csv(feature_file)
    
    if "label" not in df.columns:
        print("Error: 'label' column missing from feature matrix. Cannot train.")
        return

    print(f"    Loaded {len(df):,} pairs.")

    # 2. Train / Test Split
    print("\n[2] Splitting into train and validation sets (80/20) ...")
    # We group by source1_entity_id to avoid data leakage
    s1_ids = df["source1_entity_id"].unique()
    train_s1, val_s1 = train_test_split(s1_ids, test_size=0.2, random_state=42)

    train_df = df[df["source1_entity_id"].isin(train_s1)]
    val_df   = df[df["source1_entity_id"].isin(val_s1)]

    X_train = train_df[FEATURE_COLS]
    y_train = train_df["label"]
    X_val   = val_df[FEATURE_COLS]
    y_val   = val_df["label"]

    print(f"    Train pairs : {len(train_df):,}")
    print(f"    Val pairs   : {len(val_df):,}")

    # 3. Train XGBoost Model
    print("\n[3] Training XGBoost Classifier ...")
    
    # Scale positive weights due to class imbalance
    pos_count = (y_train == 1).sum()
    neg_count = (y_train == 0).sum()
    scale_pos_weight = neg_count / pos_count if pos_count > 0 else 1.0

    model = xgb.XGBClassifier(
        n_estimators=200,
        learning_rate=0.05,
        max_depth=6,
        scale_pos_weight=scale_pos_weight,
        eval_metric="logloss",
        random_state=42,
        n_jobs=-1
    )
    
    model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        verbose=False
    )
    print("    Training complete.")

    # 4. Feature Importance
    print("\n[4] Top 10 Most Important Features (Determined by ML):")
    importances = pd.DataFrame({
        "Feature": FEATURE_COLS,
        "Importance": model.feature_importances_
    }).sort_values(by="Importance", ascending=False)
    
    print(importances.head(10).to_string(index=False))

    # 5. Evaluate
    print("\n[5] Evaluating on Validation Set ...")
    
    # Predict probabilities
    val_df = val_df.copy()
    val_df["prob"] = model.predict_proba(X_val)[:, 1]

    # Sweep thresholds to find best F_0.5
    best_f05 = 0.0
    best_thr = 0.5
    best_p = 0.0
    best_r = 0.0

    for thr in np.arange(0.1, 0.95, 0.05):
        preds = val_df["prob"] >= thr
        tp = (preds & (val_df["label"] == 1)).sum()
        fp = (preds & (val_df["label"] == 0)).sum()
        fn = (~preds & (val_df["label"] == 1)).sum()
        
        prec = tp / (tp + fp) if (tp + fp) > 0 else 0.0
        rec  = tp / (tp + fn) if (tp + fn) > 0 else 0.0
        score = f05_score(prec, rec)
        
        if score > best_f05:
            best_f05 = score
            best_thr = thr
            best_p = prec
            best_r = rec

    print(f"  ★ Best Threshold : {best_thr:.2f}")
    print(f"    F_0.5 Score    : {best_f05:.4f}")
    print(f"    Precision      : {best_p:.4f}")
    print(f"    Recall         : {best_r:.4f}")
    
    print(f"\n{SEP}")
    print("  PERSON 3 PIPELINE COMPLETE ✓")
    print(f"{SEP}\n")


if __name__ == "__main__":
    main()
