"""
model.py
--------
Person 1 – Machine Learning Model  (integrated with main pipeline)

Trains a LightGBM classifier on the feature matrix generated by the full
blocking pipeline (output/features_sample_train.csv), evaluates on a
held-out validation split, sweeps thresholds to maximise F_0.5, and saves
the model + threshold to output/model/.

Usage:
    # Run standalone (reads from output/features_sample_train.csv)
    python src/model.py

    # Integrated (called by pipeline.py automatically during train phase)
    python src/pipeline.py --train-only
"""

import os
import sys
import json
import pandas as pd
import numpy as np

sys.path.insert(0, os.path.abspath("."))
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

import joblib
from sklearn.model_selection import train_test_split
from src.feature_engineering import FEATURE_COLS
from src.evaluate import f05_score

try:
    import lightgbm as lgb
    USE_LGB = True
except ImportError:
    import xgboost as xgb
    USE_LGB = False

SEP = "=" * 72
MODEL_DIR  = "output/model"
OUTPUT_DIR = "output"
os.makedirs(MODEL_DIR, exist_ok=True)


def train_and_evaluate(feat_df: pd.DataFrame):
    """
    Train LightGBM (or XGBoost as fallback) on the feature matrix.

    Returns (model, best_threshold, best_f05)
    """
    # ── 1. Train / validation split (group by source1 to prevent leakage) ──
    print("\n[2] Splitting into train/validation sets (80/20 by S1 entity)...")
    s1_unique = feat_df["source1_entity_id"].unique()
    train_s1, val_s1 = train_test_split(s1_unique, test_size=0.2, random_state=42)

    train_df = feat_df[feat_df["source1_entity_id"].isin(train_s1)]
    val_df   = feat_df[feat_df["source1_entity_id"].isin(val_s1)]

    X_train, y_train = train_df[FEATURE_COLS], train_df["label"]
    X_val,   y_val   = val_df[FEATURE_COLS],   val_df["label"]

    print(f"    Train pairs : {len(train_df):,}  ({(y_train==1).sum():,} pos)")
    print(f"    Val pairs   : {len(val_df):,}  ({(y_val==1).sum():,} pos)")

    # ── 2. Handle class imbalance ──────────────────────────────────────────
    pos_count = (y_train == 1).sum()
    neg_count = (y_train == 0).sum()
    scale_w   = neg_count / pos_count if pos_count > 0 else 1.0
    print(f"    scale_pos_weight = {scale_w:.1f}")

    # ── 3. Train model ─────────────────────────────────────────────────────
    print(f"\n[3] Training {'LightGBM' if USE_LGB else 'XGBoost'} Classifier...")
    if USE_LGB:
        model = lgb.LGBMClassifier(
            n_estimators=500, learning_rate=0.05, num_leaves=63,
            scale_pos_weight=scale_w, random_state=42, n_jobs=-1, verbosity=-1,
        )
    else:
        model = xgb.XGBClassifier(
            n_estimators=300, learning_rate=0.05, max_depth=6,
            scale_pos_weight=scale_w, eval_metric="logloss",
            random_state=42, n_jobs=-1,
        )

    model.fit(X_train, y_train, eval_set=[(X_val, y_val)])
    print("    Training complete.")

    # ── 4. Feature importance ──────────────────────────────────────────────
    print("\n[4] Top 10 Most Important Features:")
    importances = pd.DataFrame({
        "Feature":    FEATURE_COLS,
        "Importance": model.feature_importances_,
    }).sort_values("Importance", ascending=False)
    print(importances.head(10).to_string(index=False))

    # ── 5. Threshold sweep for best F_0.5 ─────────────────────────────────
    print("\n[5] Sweeping thresholds to find best F_0.5 ...")
    val_df = val_df.copy()
    val_df["prob"] = model.predict_proba(X_val)[:, 1]

    best_f05, best_thr, best_p, best_r = 0.0, 0.5, 0.0, 0.0
    for thr in np.arange(0.05, 0.95, 0.025):
        preds = val_df["prob"] >= thr
        tp = (preds & (val_df["label"] == 1)).sum()
        fp = (preds & (val_df["label"] == 0)).sum()
        fn = (~preds & (val_df["label"] == 1)).sum()
        prec = tp / (tp + fp) if (tp + fp) > 0 else 0.0
        rec  = tp / (tp + fn) if (tp + fn) > 0 else 0.0
        sc   = f05_score(prec, rec)
        if sc > best_f05:
            best_f05, best_thr, best_p, best_r = sc, round(float(thr), 3), prec, rec

    print(f"  ★ Best Threshold : {best_thr:.3f}")
    print(f"    F_0.5 Score    : {best_f05:.4f}")
    print(f"    Precision      : {best_p:.4f}")
    print(f"    Recall         : {best_r:.4f}")

    return model, best_thr, best_f05


def main():
    print(f"\n{SEP}")
    print(f"  PERSON 1 · MACHINE LEARNING MODEL ({'LightGBM' if USE_LGB else 'XGBoost'})")
    print(f"{SEP}\n", flush=True)

    # ── 1. Load feature matrix ─────────────────────────────────────────────
    feature_file = os.path.join(OUTPUT_DIR, "features_sample_train.csv")
    if not os.path.exists(feature_file):
        print(f"Error: Feature matrix not found at {feature_file}")
        print("Please run the full pipeline first: python src/pipeline.py --train-only")
        return

    print(f"[1] Loading features from {feature_file} ...")
    df = pd.read_csv(feature_file)
    if "label" not in df.columns:
        print("Error: 'label' column missing. Cannot train without ground truth labels.")
        return
    print(f"    Loaded {len(df):,} pairs.")
    print(f"    Positive: {(df['label']==1).sum():,}  |  Negative: {(df['label']==0).sum():,}")

    # ── Train ──────────────────────────────────────────────────────────────
    model, best_thr, best_f05 = train_and_evaluate(df)

    # ── Save ───────────────────────────────────────────────────────────────
    print(f"\n[6] Saving model and threshold to {MODEL_DIR}/ ...")
    joblib.dump(model, f"{MODEL_DIR}/model.pkl")
    with open(f"{MODEL_DIR}/threshold.json", "w") as f:
        json.dump({"threshold": best_thr, "f05": best_f05}, f)
    print(f"    Saved: model.pkl, threshold.json (threshold={best_thr}, f05={best_f05:.4f})")
    print(f"\n{SEP}")
    print("  PERSON 1 PIPELINE COMPLETE ✓")
    print(f"{SEP}\n")


if __name__ == "__main__":
    main()
